# SPDX-License-Identifier: GPL-2.0
# Core

obj-m += pinctrl-mtk-v2.o
pinctrl-mtk-v2-y += mtk-eint.o
pinctrl-mtk-v2-y += pinctrl-mtk-common-v2.o
pinctrl-mtk-v2-y += pinctrl-paris.o
obj-m += pinctrl-mtk-common-v2_debug.o

obj-$(CONFIG_PINCTRL_MTK)	+= pinctrl-mtk-common.o
obj-$(CONFIG_PINCTRL_MTK_MOORE) += pinctrl-moore.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT2701)	+= pinctrl-mt2701.o
obj-$(CONFIG_PINCTRL_MT2712)	+= pinctrl-mt2712.o
obj-$(CONFIG_PINCTRL_MT8135)	+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8127)	+= pinctrl-mt8127.o
obj-$(CONFIG_PINCTRL_MT6765)	+= pinctrl-mt6765.o
obj-$(CONFIG_PINCTRL_MT6779)	+= pinctrl-mt6779.o
obj-$(CONFIG_PINCTRL_MT6797)	+= pinctrl-mt6797.o
obj-$(CONFIG_PINCTRL_MT6855)	+= pinctrl-mt6855.o
obj-$(CONFIG_PINCTRL_MT7622)	+= pinctrl-mt7622.o
obj-$(CONFIG_PINCTRL_MT7623)	+= pinctrl-mt7623.o
obj-$(CONFIG_PINCTRL_MT7629)	+= pinctrl-mt7629.o
obj-$(CONFIG_PINCTRL_MT8167)	+= pinctrl-mt8167.o
obj-$(CONFIG_PINCTRL_MT8173)	+= pinctrl-mt8173.o
obj-$(CONFIG_PINCTRL_MT8183)	+= pinctrl-mt8183.o
obj-$(CONFIG_PINCTRL_MT8192)	+= pinctrl-mt8192.o
obj-$(CONFIG_PINCTRL_MT8516)	+= pinctrl-mt8516.o
obj-$(CONFIG_PINCTRL_MT6397)	+= pinctrl-mt6397.o
