ifneq ($(filter m y,$(CONFIG_INPUT_ILI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DILI_SENSOR_EN
endif

ifneq ($(filter m y, $(CONFIG_ILITEK_STOWED_MODE_SUPPORT)),)
	EXTRA_CFLAGS += -DILI_STOWED_SUPPORT
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DILI_DOUBLE_TAP_CTRL
	EXTRA_CFLAGS += -DILI_PRIMARY_NODE
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_RESUME_BY_DDI)),)
EXTRA_CFLAGS += -DILI_CONFIG_RESUME_BY_DDI
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_CHARGER)),)
EXTRA_CFLAGS += -DILI_CONFIG_MTK_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DILI_MTK_CHECK_PANEL
endif

ifneq ($(filter m y,$(CONFIG_ILI_TOUCH_LAST_TIME)),)
	EXTRA_CFLAGS += -DILI_TOUCH_LAST_TIME
endif

obj-$(CONFIG_TOUCHSCREEN_ILITEK_CHIPSET) := ilitek_v3_mmi.o
ilitek_v3_mmi-objs += ilitek_v3.o
ilitek_v3_mmi-objs += ilitek_v3_spi.o
ilitek_v3_mmi-objs += ilitek_v3_qcom.o
ilitek_v3_mmi-objs += ilitek_v3_ic.o
ilitek_v3_mmi-objs += ilitek_v3_touch.o
ilitek_v3_mmi-objs += ilitek_v3_mp.o
ilitek_v3_mmi-objs += ilitek_v3_hostdl.o
ilitek_v3_mmi-objs += ilitek_v3_node.o

