ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_0FLASH_V2_MMI) := focaltech_0flash_mmi_v2.o
focaltech_0flash_mmi_v2-objs += focaltech_core.o
focaltech_0flash_mmi_v2-objs += focaltech_esdcheck.o
focaltech_0flash_mmi_v2-objs += focaltech_ex_fun.o
focaltech_0flash_mmi_v2-objs += focaltech_ex_mode.o
focaltech_0flash_mmi_v2-objs += focaltech_flash.o
focaltech_0flash_mmi_v2-objs += focaltech_gesture.o
focaltech_0flash_mmi_v2-objs += focaltech_point_report_check.o
focaltech_0flash_mmi_v2-objs += focaltech_spi.o

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DFOCALTECH_SENSOR_EN
endif

ifneq ($(filter m y,$(CONFIG_FTS_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DFTS_MTK_CHECK_PANEL
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_MTK_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_FTS_IRQ_DIS_FOR_RESET)),)
	EXTRA_CFLAGS += -DFTS_IRQ_DISABLE_FOR_RESET
endif
