# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_BQ25980_MMI)			+= bq25980_mmi/
obj-$(CONFIG_MMI_DECRETE_CHARGER_CP_QC3P)	+= mmi_decrete_charger_cp_qc3p/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE)		+= qpnp_adaptive_charge/
obj-$(CONFIG_SC8551_MMI)			+= sc8551_mmi/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
