# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTK_TEE_GP_COORDINATOR) += gpapi/
obj-$(CONFIG_OPTEE) += optee/
obj-$(CONFIG_AMDTEE) += amdtee/
obj-$(CONFIG_TEE_PERF_SUPPORT) += teeperf/
obj-$(CONFIG_TRUSTONIC_TEE_SUPPORT) += gud/
obj-$(CONFIG_MICROTRUST_TEE_SUPPORT) += teei/
