ifneq ($(filter m y,$(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DNVT_SENSOR_EN
endif
ifneq ($(filter m y, $(CONFIG_STOWED_MODE_SUPPORT)),)
	EXTRA_CFLAGS += -DNVT_STOWED_MODE_SUPPORT
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DNVT_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y, $(CONFIG_NOVATEK_MTK_SPI)),)
	EXTRA_CFLAGS += -DCONFIG_NVT_MTK_SPI
endif

ifneq ($(filter m y,$(CONFIG_NOVA_TOUCH_LAST_TIME)),)
	EXTRA_CFLAGS += -DNVT_TOUCH_LAST_TIME
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCFG_MTK_PANEL_NOTIFIER
endif

ifneq ($(filter m y,$(CONFIG_NOVA_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DNVT_MTK_CHECK_PANEL
endif
ifneq ($(filter m y,$(CONFIG_NVT_LCM_ESD_NOTIFIER)),)
        EXTRA_CFLAGS += -DNVT_LCM_ESD_NOTIFIER
endif
ifneq ($(filter m y,$(CONFIG_NVT_ESD_RST_SUPPORT)),)
        EXTRA_CFLAGS += -DNVT_ESD_RST_SUPPORT
endif
ifneq ($(filter m y,$(CONFIG_NVT_ESD_RECOVERY_SUPPORT)),)
        EXTRA_CFLAGS += -DNVT_ESD_RECOVERY_SUPPORT
endif

ifneq ($(filter m y,$(CONFIG_NOVA_CHECK_DEVICE_BOOTMODE)),)
	EXTRA_CFLAGS += -DNVT_CHECK_DEVICE_BOOTMODE
endif

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
	EXTRA_CFLAGS += -DNVT_BUILD_USERDEBUG
endif

obj-$(CONFIG_TOUCHSCREEN_NVT_CHIPSET) := nova_0flash_mmi_v2.o
nova_0flash_mmi_v2-objs += nt36xxx.o
nova_0flash_mmi_v2-objs += nt36xxx_ext_proc.o
nova_0flash_mmi_v2-objs += nt36xxx_fw_update.o
nova_0flash_mmi_v2-objs += nt36xxx_mp_ctrlram.o
