obj-$(CONFIG_MMI_DECRETE_CHARGER_CP_QC3P) += mmi_decrete_charger_cp_qc3p.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_class.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_core.o
mmi_decrete_charger_cp_qc3p-objs += mmi_pump_charger.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_pump_policy.o
mmi_decrete_charger_cp_qc3p-objs += mtk_pmic_charger.o
mmi_decrete_charger_cp_qc3p-objs += pps.o
